In [1]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)

In [2]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
pip install matplotlib

Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
import pandas as pd
import numpy as np

np.random.seed(42)

df = pd.DataFrame({
    "Age": np.random.randint(18, 65, 100),
    "Income": np.random.randint(20000, 150000, 100),
    "Experience": np.random.randint(0, 35, 100),
    "CreditScore": np.random.randint(300, 850, 100),
    "LoanAmount": np.random.randint(5000, 500000, 100),
    "AnnualSpend": np.random.randint(1000, 100000, 100),
    "Savings": np.random.randint(500, 200000, 100),
    "Debt": np.random.randint(0, 300000, 100),
    "Transactions": np.random.randint(10, 500, 100),
    "Target": np.random.randint(0, 2, 100)
})
print(df.shape)

(100, 10)

In [8]:
df.head()

,Age,Income,Experience,CreditScore,LoanAmount,AnnualSpend,Savings,Debt,Transactions,Target
0,56,22695,24,697,273093,39304,155286,105787,249,0
1,46,144375,32,576,188062,70449,38602,162993,468,0
2,32,68190,0,803,399366,83986,74960,295451,380,1
3,60,25258,26,691,225552,90643,103134,127016,120,0
4,25,107538,12,434,105235,21764,90430,266979,258,0

In [9]:
df.tail()

,Age,Income,Experience,CreditScore,LoanAmount,AnnualSpend,Savings,Debt,Transactions,Target
95,24,41834,34,419,368186,22545,119656,276532,372,0
96,26,38047,15,357,360754,22689,161275,5569,248,1
97,41,46105,32,645,256492,12174,9837,69836,283,0
98,18,95766,3,773,370835,89461,46927,104573,303,0
99,61,35707,32,416,496072,10348,62029,258090,236,1

In [17]:
from sklearn.decomposition import PCA # Importing of PCA

In [18]:
from sklearn.preprocessing import StandardScaler # Importing of Scaler

In [19]:
scaler = StandardScaler() # Declaration of Scaler
x = df.drop(columns=['Target'])
x_scaled = scaler.fit_transform(x)

In [21]:
pca = PCA(n_components=0.95) # Declaration of PCA
x_reduced = pca.fit_transform(x_scaled)
#print(x_reduced)

In [25]:
pca_df = pd.DataFrame(
    x_reduced,
    columns=[f"PC{i+1}" for i in range(x_reduced.shape[1])]
)

print(pca_df.shape)

(100, 9)